---
name: dispatch

defaults:
  run:
    shell: bash

on:
  push:

jobs:
  dispatch-dicompute:
    runs-on: ubuntu-latest
    steps:
      - name: notify goreleaser-cross with new release
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.GORELEASER_ACCESS_TOKEN }}
          repo: dicompute-network/homebrew-tap
          workflow: dicompute
          ref: refs/heads/main
          inputs: '{ "tag" : "${{ env.RELEASE_TAG }}" }'
